# AUTOGENERATED file - generate with tools/fetch_and_convert_message_map.sh
# This file maps numeric message IDs to AS message type names (strings).
# Generation failed during automated run (likely due to network restrictions), so this
# placeholder keeps the module importable. Re-run the script in a networked environment
# to populate the mapping with real values.
MESSAGE_MAP = {}
